% -------------------------------------------------------------------
%  Generated by MATLAB on 10-Jan-2022 02:11:02
%  MATLAB version: 9.11.0.1809720 (R2021b) Update 1
% -------------------------------------------------------------------
saveVarsMat = load('exercises1.mat');

a = 9.8;

e = saveVarsMat.e; % <1x1 MException> unsupported class

h = 381;

t = 8.8178853497205516;

time_effect = 1.8367346938775508;

timenoacc = 20.248299319727892;

total = 22.085034013605444;

v = 86.415276427261418;

xacc = 16.530612244897956;

xnoac = 364.46938775510205;

clear saveVarsMat;
